lista = []
lista.append(10)
lista.append(12)
lista.append(16)
lista.append(17)
lista.append(1)
lista.append(90)
print("Minha lista")
print(lista)
print("====================")
print("Adicionando valor na lista na posição 2")
lista.insert(2,33)
print(lista)
print("====================")
print("Descobrindo a posiçao do elemento 1 na lista")
print(lista.index(1))
print("====================")
print("Removendo o valor através da posição do elemento na lista")
var = lista.index(1)
lista.pop(var)
print(lista)